### ISSUE TITLE
usage of ffmpeg/av

### ISSUE THREAD

**Issue by pliablepixels** [ozonesecurity/ozonebase#11]
need to make sure we are compliant with ffmpeg licensing https://www.ffmpeg.org/legal.html 
In other words, we need to be able to git clone and build our own ffmpeg lib with the right compile options as per the url above. This will also avoid the endless loops of diff. host system ffmpeg versions and issues.

**Comment by pliablepixels** [comment]
This should be resolves when Phil merges ffmpeg-branch

**Comment by web2wire** [comment]
Merged.
