### ISSUE TITLE
submodule versions do not match settings in .gitmodules

### ISSUE THREAD

**Issue by phirestalker** [ozonesecurity/ozonebase#152]
output: 
`git submodule update --init --recursive
Submodule path 'externals/dlib': checked out '97151133b07c434c16222a2e11ec735ab19e2540'
Submodule path 'externals/ffmpeg': checked out 'da4ea971617351600f49437bc9d489e650b4de38'
Submodule path 'externals/json': checked out '0f04e42dd5ee53af466e25a82667fe4c3b039775'
Submodule path 'externals/openh264': checked out '9e75838c8638c48a32b15c73c9da7b1fe942fd5f'
`

when I look up the commit for dlib, it is dated before the current master. I am unable to determine how it is choosing what version to check out.

**Comment by web2wire** [comment]
I may be misunderstanding your question but the commits for the third party libraries can be found in the externals directory. The interfaces and capabilities for those libraries change so fast that we just fixed on a set that worked together. You can go into the individual external directories and pull down more recent commits if you like.

**Comment by pliablepixels** [comment]
Ah, I think the confusion is that @phirestalker had to manually add a commit that was a year old to get it to compile. Given we don't mandate a version in Cmake for dlib, I assumed we are not checkpointing a specific version. As you have mentioned here, they are fixed in `externals` which I forgot. That explains why he had this problem. I suppose we should change the commit tag to at least this version.

**Comment by phirestalker** [comment]
ok I manually pulled down a later version, but as soon as I run the build script it pulls down the same old version which is not specified in .gitmodules. If the setting for what version to download is not in .gitmodules then where is it?

**Comment by web2wire** [comment]
You should be able to update the submodules by following the process detailed in the answer given here (https://stackoverflow.com/questions/5828324/update-git-submodule-to-latest-commit-on-origin). The main thing is that unless you commit it to your branch then that change won't stick.

**Comment by phirestalker** [comment]
ok, I updated the submodules. I have bumped dlib to current master and bumped ffmpeg to release/3.1

I have updated the code to comply with the new ffmpeg version, but I am stumped by one error. I was wondering if I could get a little help.

the error is:
`/Users/phire/ozonebase/server/src/processors/ozMatrixVideo.cpp:135:87: warning:pointer to a function used in arithmetic [-Wpointer-arith]
         const AVPixFmtDescriptor *interFormatDesc = av_pix_fmt_desc_get[mAVPixelFormat];
                                                                                       ^
/Users/phire/ozonebase/server/src/processors/ozMatrixVideo.cpp:135:87: error: cannot convert 'const AVPixFmtDescriptor* (*)(AVPixelFormat)' to 'const AVPixFmtDescriptor*' in initialization
/Users/phire/ozonebase/server/src/processors/ozMatrixVideo.cpp:149:36: warning:comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for ( int i = 0; i < mProviderList.size(); i++ )`

I was all set up to commit when I finished, but I am stumped with this error.

**Comment by phirestalker** [comment]
ok, my font is too small. I see what the problem is. They discontinued the call your code used and I changed to  av_pix_fmt_desc_get which is a function and not an array. I could not see the difference between [ and ( with the small type on my screen.

**Comment by phirestalker** [comment]
finished
[https://github.com/ozonesecurity/ozonebase/pull/153](url)
