### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by chjomoon** [ozonesecurity/ozonebase#158]
[ 53%] Performing configure step for 'ffmpeg'
cd /home/build/ozonebase/ffmpeg-prefix/src/ffmpeg-build && PKG_CONFIG_PATH=/home/build/ozonebase/buildroot/home/build/ozoneroot/lib/pkgconfig /home/build/ozonebase/externals/ffmpeg/configure --enable-shared --libdir=/home/build/ozonebase/buildroot/home/build/ozoneroot/lib --prefix=/home/build/ozonebase/buildroot/home/build/ozoneroot --enable-libopenh264 --extra-ldflags=-L/home/build/ozonebase/buildroot/home/build/ozoneroot/lib --extra-cflags=-I/home/build/ozonebase/buildroot/home/build/ozoneroot/include/wels --pkg-config-flags=--define-variable=libdir=/home/build/ozonebase/buildroot/home/build/ozoneroot/lib --pkg-config-flags=--define-variable=includedir=/home/build/ozonebase/buildroot/home/build/ozoneroot/include
Out of tree builds are impossible with config.h in source dir.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
CMakeFiles/ffmpeg.dir/build.make:108: recipe for target 'ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure' failed
make[2]: *** [ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure] Error 1
make[2]: Leaving directory '/home/build/ozonebase'
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/ffmpeg.dir/all' failed
make[1]: *** [CMakeFiles/ffmpeg.dir/all] Error 2
make[1]: Leaving directory '/home/build/ozonebase'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2

Hi I got an issue above while compiling.

After copy and paste libv4l2.pc, fontconfig.pc, then typed command $ make , showing this error message.

is there anything I missing while I compile this?

**Comment by pliablepixels** [comment]
Hi, ozone is not actively maintained. I'll put in a GitHub notice to reflect that. With respect to your error, if @web2wire is available he might want to post.

**Comment by chjomoon** [comment]
@pliablepixels I fix this issue after Ubuntu switched to 16.04, it works.
