### ISSUE TITLE
Base URL

### ISSUE THREAD

**Issue by chjomoon** [ozonesecurity/ozonebase#159]
Hi, I downloaded ozone on my ubuntu rn.
it's bit confused few things to run ozone for the first time.
I compiled and ran starter_example, then running html file. 
Thus, it is failed to load video sources from sftp.
To set the $scope.baseurl from html file, which location should I exactly put it in?
For example, if my linux server ip is 192.111.23.231, is it correct to put this ip address? 
or adding the location that "./starter_example" stored?

Please, let me know the details
Thanks

**Comment by pliablepixels** [comment]
base url is the IP and port where you are running the starter_example C++ program.

**Comment by chjomoon** [comment]
@pliablepixels Thanks. The ip camera is successfully played on html. But I'm getting an issue while running a program, the video that contains some options such as  does not play properly.
    Options peopleOptions;
    peopleOptions.add( "realtime", true );
    peopleOptions.add( "loop", true );
    AVInput people( "people", camera1, peopleOptions );
    app.addThread( &people );

Which part should I change to implement the video included options?
