### ISSUE TITLE
Duplicate ozConfigDefines.h

### ISSUE THREAD

**Issue by knight-of-ni** [ozonesecurity/ozonebase#35]
There are two copies of ozConfigDefines.h in this project:
server/src/ozConfigDefines.h
server/src/base/ozConfigDefines.h

This is confusing. One of them should be deleted. The contents of these files are quite a bit different from one another so I cannot tell which one is "right" simply based on their contents.

Both the cmake and autotools build systems use the one under the base subfolder.

Anyone have any thoughts before I nuke server/src/ozConfigDefines.h ?

**Comment by pliablepixels** [comment]
Yup, lets delete it. Looks like @web2wire did a bit of pruning in base/ to remove eyeZM stuff. Still needs more pruning, which can be another future PR
