### ISSUE TITLE
suggest adding a namespace of oz to our APIs

### ISSUE THREAD

**Issue by pliablepixels** [ozonesecurity/ozonebase#5]
so our example code can look like:

```
oz::Application app
```

and so forth, for all public APIs

**Comment by pliablepixels** [comment]
This would also include renaming all "zm" prefixed functions to use oz namespace

**Comment by SteveGilvarry** [comment]
👍 oz makes everything better

**Comment by pliablepixels** [comment]
Step 1 done - filenames and classes with zm renamed to oz. Namespacing is TBD and I believe @web2wire is doing that

**Comment by knight-of-ni** [comment]
Ugh, good idea, but I wish this was done after I finished writing CMakeLists.txt. Now I have to start over.

**Comment by pliablepixels** [comment]
Andy pick up zm2oz.pl  in scripts- and add the file extensions of your
files. It should translate.

**Comment by pliablepixels** [comment]
It was agreed that @web2wire will namespace with oz
